<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CommonModule">
      <HintPath>..\CommonModule\bin\Release\net6.0\CommonModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
